### ISSUE TITLE
How Do I Interpret This Error

### ISSUE THREAD

**Issue by drag05** [rstudio/tinytex#406] opened 2023-03-16 18:35 UTC
When compliling the .tex file to pdf document I get this error:

```
Package: fontspec 2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX

! Fatal Package fontspec Error: The fontspec package requires either XeTeX or
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex" instead of
(fontspec)                      "latex" or "pdflatex".
```  
However, my yaml header sets `xelatex` as engine:

```
output: 
  pdf_document: 
    latex_engine: xelatex
    df_print: paged
    keep_tex: yes
    fig_caption: yes
    toc: yes
    extra_dependencies: float
    highlight: tango
```
I have re-installed `xelatex` and run `tlmgr_update()` to no avail.
Please advise, thank you!

**Comment by cderv** [comment] 2023-04-07 10:38
Can you share a document with this issue ? 

setting `latex_engine` as you have done should work for such issue. Maybe this is different. Probably a LaTeX issue also, which means not related to the R package and requires more information about the document content

**Comment by drag05** [comment] 2023-04-07 21:24
@cderv Unable to share the original Rmd (proprietary). 
I have reproduced the header of original Rmd using the default "New R markdown" file in RStudio. It could be a conflict in my `\usepackage` list. Please find attached examples.docx (couldn't attach Rmd) which throws the same error. 
When running the `tex`, package `fontspec.sty` is also referenced in the error.

[example.docx](https://github.com/rstudio/tinytex/files/11181621/example.docx)

Thank you!

**Comment by cderv** [comment] 2023-04-11 08:16
> Please find attached examples.docx (couldn't attach Rmd)

You can add the Rmd file in a Zip and attach the zip file. Or you can share Rmd as a Gist (https://gist.github.com/) easily, if not in a Github repo

You can also just copy paste in the issue following the guide: https://yihui.org/issue/#please-format-your-issue-correctly

I would prefer you share like this because in the Docx the indentation does not seem to be kept so unsure about your document. 

Several comments / questions though:

* `toc_includes:` : where does it come from ? Just not sure I remember this options
* You have a lot of content in `header_includes` - is that necessary ? There is already a lot of packages and feature available with Pandoc's template. Did you try find if one of them is responsible ? this would help reduce your example to a more minimum example. 
* `mainfont: Palatino Linotype` I suspect the issue happens only when using this fonts ? Or does it happens when no fonts ? 
* `\rhead{\includegraphics[width=2.5cm]{C:/Spectrus/logo.png}}` -> I don't have this png file, so you're example can't really be run on my side. 

Overall, it would help understand the problem if you can reduce a bit more this example to the minimal set of config that have the issue on your side. Thanks !

**Comment by drag05** [comment] 2023-04-11 16:16
@cderv 

I have attached a MRE zip file. 
Regarding your questions:
- `toc includes`:
it includes list of figures and list of tables (`lof`, `lot`)
- content in `header includes:` require packages for header/footer layout, title vertical adjustment, as well as for page body layout, necessary for reporting. The package specified in error is `fontspec`. 
Other packages are necessary for rotating wide tables to landscape (by the way: `pander` cannot rotate tables containing down score ("_") in their caption. But this is another issue ...) 
- `main font` has no impact. The error appears with `main font` "Calibri" and without `main font` at all (as in attached example)
- removed the logo

Please find attached minimum reproducible example with only one latex package , `fontspec` , attached. The error persists. It disappears once this package is removed which, brings us back to the issue.

Thank you!

[example.zip](https://github.com/rstudio/tinytex/files/11202432/example.zip)

**Comment by cderv** [comment] 2023-04-11 22:10
You doc has 
```yaml
toc_includes:
lof: yes
lot: yes
````
without specific indentation. `toc_includes` is empty. Not sure where it came from - just curious as I don't think it is linked to your issue

Thanks for the minimal reprex. I can reproduce without any issue when `latex_engine: xelatex`. 

I can reproduce your error message when `latex_engine: pdflatex` though. 

Do you have `xelatex` available ? Can you check the indentation of your YAML header to be sure the the `latex_engine` key is picked up ? You could try `rmarkdown::render(..., output_options  = list(latex_engine = "xelatex"))` also to see if this is a YAML problem

I don't see any reproducible issue unfortunately so probably something in the file or your setup. 

Does the minimal example you shared no working for you ? 

More simple one: 
````markdown
---
title: "Example"
output: 
  pdf_document: 
    latex_engine: xelatex
    keep_tex: yes
header-includes: 
 \usepackage{fontspec}
---

# Content
````

Does it error for you ?

**Comment by drag05** [comment] 2023-04-11 23:16
@cderv 
So far `lot` and `lof` worked exactly how they were shown in example. No error or indentation requirement would pop-up.
However, the error was thrown when `\usepackage{fontspec}` line was present and disappeared when was taken out (this error only appeared when rendering the `tex` to pdf and not when knitting the Rmd to pdf) 

Now:
I have inserted indentations for `lof` and `lot`

```
toc_includes:
  lof: yes
  lot: yes
```
And it seems to be working. Rendering the `tex` to pdf no longer throws the error when  `\usepackage{fontspec}` is present.

I think the cause of the error was found. I am closing the issue.

Thank you!

**Comment by drag05** [comment] 2023-04-11 23:29
@cderv  It seems I have closed the issue too soon: I have run one of my documents with indented `lof` and `lot`. As result, the list of figures and tables no longer appear in the TOC. Reverted without indentation and the figures and tables appeared again in the TOC. Should I raise another issue?
Thank you!

**Comment by cderv** [comment] 2023-04-12 06:44
Can you tell where `toc_includes` is used ? Where this variable is used ?
I don't know or don't remember this variable. `lot` and `lof` [are from Pandoc](https://pandoc.org/MANUAL.html#front-matter) and should be first level in YAML as pandoc's variables. What I can says is that 
````yaml
toc_includes:
lof: yes
lot: yes
````
does not seem right as `toc_includes` has no value here. 

> Should I raise another issue?

What other error exactly ? Can we check this `toc_includes` thing before. 

Overall I am not following anymore what the issue here. We asked for minimal example for that purpose also - stay focus on the issue. So does the fontspec issue still happening ? 

If it was fixed by some YAML change, then it is possibly an indentation issue. Please check that.

**Comment by drag05** [comment] 2023-04-12 23:19
@cderv 
Please find attached MRE 
[example.zip](https://github.com/rstudio/tinytex/files/11216789/example.zip)
covering 
- where the List Of Figures and List of Tables appear on page (under TOC)
- how table landscape is impacted by the presence of "_" in table caption

**Comment by cderv** [comment] 2023-04-13 11:44
@drag05 I still missing some information. 

Your example has `\rhead{\includegraphics[width=2.5cm]{C:/Spectrus/logo.png}}` so it is not a MRE - I can't run this on my side. 

> where the List Of Figures and List of Tables appear on page (under TOC)

I don't understand what is the issue here. You still have `toc_includes` though with no value assigned. I really don't know what this is used for. 

> how table landscape is impacted by the presence of "_" in table caption

This is a different issue right ? not more fontspec thing ? We try to keep issue scope to one problem. We can't answer every question about How to do something with LaTeX 

You have Q&A website like stackoverflow or https://community.rstudio.com/ for this. Please consider asking there next time. 

When you do 
````markdown
\begin{landscape}

<some markdown content here  only, or mixed with code chunks>

\end{landscape}
````

you are creating a LaTeX block. The Markdown inside won't be processed as Markdown to be converted to LaTeX and will be used asis in the `.tex` file. This does not create the output you want , and has issue because `_` is a special character in LaTeX and requires escaping. 

Anyhow, we document how to use environment in LaTeX using custom blocks https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html#custom-blocks or you need to use [raw content](https://bookdown.org/yihui/rmarkdown-cookbook/raw-content.html) for LaTeX parts. 

Using the former this is what you can do with the feature we added.

````markdown
::: {.landscape latex=1}
```{r cars, eval = TRUE}
pander::pander(cars[1:5, ], caption = 'caption_with_downscore')
```
:::
````

Oterhwise use 
````markdown
`\begin{landscape}`{=latex}

```{r cars, eval = TRUE}
pander::pander(cars[1:5, ], caption = 'caption_with_downscore')
```

`\end{landscape}`{=latex}
````


I'll close this issue now. Please to reopen one if you still have some problem or ask on the RStudio / Posit Community

thanks

**Closed by cderv** 2023-04-13 11:44 UTC
